#!/bin/bash

# *************************************************
# findbugs (introcs)
# Hayk Martirosyan
# -------------------
# Easy-to-understand wrapper for using findbugs.
# *************************************************

# This must match the unzipped folder name of findbugs
FINDBUGS=findbugs-?.?.?

# This must match the specified install directory
INSTALL=~/introcs

# This is the bin directory
BIN=bin

# Sets the paths to the findbugs jar and xml files
jar=${INSTALL}/${FINDBUGS}/lib/findbugs.jar
xml=${INSTALL}/${FINDBUGS}/findbugs.xml
aux=${INSTALL}/stdlib.jar:${INSTALL}/java3d/j3dcore.jar:${INSTALL}/java3d/j3dutils.jar:${INSTALL}/java3d/vecmath.jar:${INSTALL}/java3d/gluegen-rt.jar:${INSTALL}/java3d/jogl.jar

# If there are no arguments
if [ ! -n "$1" ]; then
	echo 'Specify .class or .jar files as arguments.'
	echo "Usage: 'findbugs Test.class'"
	exit
fi

# If the first argument is a .class file that exists, runs findbugs
if [ "${1##*.}" = "class" ]; then
	if [ -e "$1" ]; then
		echo "Running findbugs on $*:"
		java -jar ${jar} -textui -longBugCodes -exclude ${xml} -auxclasspath ${aux} $*
	else
		echo "File not found! Make sure you are specifying the path correctly."
		echo "The filename is case sensitive."
	fi
	exit
fi

# If the first argument is a .jar file that exists, runs findbugs
if [ "${1##*.}" = "jar" ]; then
	if [ -e "$1" ]; then
		echo "Running findbugs on $*:"
		java -jar ${jar} -textui -longBugCodes -exclude ${xml} -auxclasspath ${aux} $*
	else
		echo "File not found! Make sure you are specifying the path correctly."
		echo "The filename is case sensitive."
	fi
	exit
fi

echo "Findbugs needs .class or .jar files as arguments!"
echo "The filename is case sensitive."
exit
